version: '3.8'

services:
  interface:
    container_name: rustobot-interface
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    profiles:
      - development
      - production
      - test
    # The command use bash to verify the COMPOSE_PROFILES variable and run the appropriate command.
    command: bash -c "if [ "$COMPOSE_PROFILES" = "production" ]; then \trunk --config Trunk.toml serve --release; \elif [ "$COMPOSE_PROFILES" = "development" ]; then \trunk --config Trunk.toml serve; \fi"

  server:
    container_name: rustobot-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8393:8393"
    profiles:
      - development
      - production
      - test
    # The command use bash to verify the COMPOSE_PROFILES variable and run the appropriate command.
    command: bash -c "if [ "$COMPOSE_PROFILES" = "production" ]; then \cargo run --release; \elif [ "$COMPOSE_PROFILES" = "development" ]; then \cargo watch -w src -x 'run'; \fi"

  database:
    container_name: rustobot-database
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rustobotdb"
    ports:
      - "5432:5432"
    profiles:
      - development
