[package]
name = "interface"
version = "0.0.1"
authors = ["Vinicios Lugli <vinicioslugli@gmail.com>"]
edition = "2021"

[dependencies]
yew = { version="0.20.0", features = ["csr"] }
js-sys = "0.3.61"
gloo = "0.8.0"
wasm-bindgen = "0.2.84"
serde = "1.0.159"
