# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - ".gitignore"
      - ".github/**"
      - "*.code-workspace"
    branches:
      - main
      - feat/**
      - fix/**
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - ".gitignore"
      - ".github/**"
      - "*.code-workspace"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "docker-test"
  docker-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Timeout for the job
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Update from branch
      - name: Checkout
        uses: actions/checkout@v3

      # Build the docker containers
      - name: Build containers
        run: COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" build

      ### Run the containers tests for each workspace

      - name: Test interface container
        run: |
          COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" run --rm interface cargo test
          COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" run --rm interface trunk build

      - name: Test server container
        run: docker-compose -f "docker-compose.yml" run --rm server cargo test

      # Stop containers if any of the previous steps failed or if the job was cancelled
      - name: Stop containers
        if: always()
        run: COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" down
