# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - feat/**
      - fix/**
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "docker_test"
  docker_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Timeout for the job
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Update from branch
      - name: Checkout
        uses: actions/checkout@v1

      # Start the docker containers in test
      - name: Start containers
        run: COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" up -d --build

      # Exec test commands in each workspace
      - name: Run tests
        run: |
          COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" exec interface cargo test
          COMPOSE_PROFILES=test docker-compose -f "docker-compose.yml" exec server cargo test

      # Stop containers
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
